# Generated by Django 6.0.4 on 2026-08-29 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="User must be at least 18 years old."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Age cannot be greater than 100."
                    ),
                ]
            ),
        ),
    ]
